# remote_theme: jekyll-theme-agency

url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Minh Anh's
email: minhanhcao.1234@gmail.com
description: "Cao Thi Minh Anh's portfolio."


# Team names, titles and social links
people:
- name: Minh Anh (Mia)
  pic: 1
  position: Portfolio's owner
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# - name: Larry Parker
#   pic: 2
#   position: Lead Marketer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: linkedin
#       url: #

# - name: Diana Petersen
#   pic: 3
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# # Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket 
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Hanoi, Vietnam

# Build settings
markdown: kramdown
permalink: pretty
